name: Build packages

on:
  push:
    paths-ignore:
      - 'README.md'

    branches:
      - master

jobs:
  ubuntu:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: philj56/tofi-debian-build

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install llvm clang devscripts debhelper meson scdoc \
          ninja-build libfreetype-dev libharfbuzz-dev libcairo-dev \
          libpango1.0-dev libwayland-dev wayland-protocols libxkbcommon-dev \
          python3-pip

          sudo pip3 install --upgrade meson

      # The version of GCC on Ubuntu 20.04 is too old to recognise
      # [[attribute]] syntax, so use clang instead.
      #
      # Conversely, there's a bug somewhere in debhelper with clang on
      # Ubuntu 22.04, so use GCC there.
      - name: Set clang as default compiler on Ubuntu 20.04
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: sudo update-alternatives --set cc $(which clang)

      - name: Build package
        run: ./gendeb.sh

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: tofi-${{ matrix.os }}
          path: tofi-debian/tofi_0.3.1-1_amd64.deb

